SELECT *
FROM Achievement_AGT AGT
LEFT JOIN Achievement A ON A.ID = AGT.ID
WHERE A.ID IS NULL AND AGT.Category_AGT_ID != 21 AND AGT.Name NOT LIKE '%Realm First%' AND AGT.TRACKING_FLAG = 0
AND AGT.Category_AGT_ID != 92 AND AGT.ID != 4496
ORDER BY AGT.Category_AGT_ID